### ISSUE TITLE
Let players drop items from their inventory

### ISSUE THREAD

**Issue by cbcerquiaga** [cbcerquiaga/YouMeAndTheEndOfTheWorld#18]

**Comment by UngratefulFool** [comment]
In order to do this we would need the player to either drop an item at random (really just a test if we can do it) or select an item then drop it. I cannot think of an easy way to select an item unless we make 1,2,3,... 0 be the inventory selection, but we have two players, or there be an UI for them to select items. Both will require us to key bind a drop button. Any thoughts on what I should do?

**Comment by cbcerquiaga** [comment]
I think we may have to wait until we get the UI working, because you're totally right.

**Comment by UngratefulFool** [comment]
I have added the framework for this in playerProperties.gd, now the only thing to do is add a method that will take the selected object and add it at the location of the player, or near the player, like in front.

**Comment by UngratefulFool** [comment]
Completed, I just added the ability for the player to drop each item that is in their inventory starting at index 0. We can change this by changing the selected item later on.
