### ISSUE TITLE
Make action buttons open doors, pick up items, etc

### ISSUE THREAD

**Issue by cbcerquiaga** [cbcerquiaga/YouMeAndTheEndOfTheWorld#23]
Right now, players can just run into things and get them- we should definitely make it so that if a player is close enough to an item and then pushes an action button (action 1 for now?) that then they pick up the item/open the door. Ideally, you wouldn't be able to run around holding the action button, and later we should add button prompts and/or hovering item names when a player is within range of a potentially actionable item.

**Comment by UngratefulFool** [comment]
Currently I believe a way to do this would be to allow the player to pass through collisions boxes, then when they press the action button, if they are in a collision box then have that item handle the collision. This should work since the player is constantly moving Vector2D(0,0) and if there is a collision box under them they should collide.

**Comment by UngratefulFool** [comment]
Done, but there is a bug, the player moves to the last know "safe area" when they press the pickup button. This is due to their collision box now colliding with the item which it did not when they were moving. Also I did not add doors because that would require a few more modifications to their collision box, but I will do that next.
